// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// cppbr
arma::mat cppbr(int iter, arma::vec y, arma::mat X, double prior_a, double prior_b, arma::vec prior_mu, arma::vec prior_prec);
RcppExport SEXP blim_cppbr(SEXP iterSEXP, SEXP ySEXP, SEXP XSEXP, SEXP prior_aSEXP, SEXP prior_bSEXP, SEXP prior_muSEXP, SEXP prior_precSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type iter(iterSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type prior_a(prior_aSEXP);
    Rcpp::traits::input_parameter< double >::type prior_b(prior_bSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_mu(prior_muSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type prior_prec(prior_precSEXP);
    __result = Rcpp::wrap(cppbr(iter, y, X, prior_a, prior_b, prior_mu, prior_prec));
    return __result;
END_RCPP
}
