# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppbr <- function(iter, y, X, prior_a, prior_b, prior_mu, prior_prec) {
    .Call('blim_cppbr', PACKAGE = 'blim', iter, y, X, prior_a, prior_b, prior_mu, prior_prec)
}

